import { CLUB_DATA } from '../constants/clubs';
import { StandingsTable, Match, Scorer, TeamDetail, HeadToHead } from '../types';

export const CURRENT_MATCHWEEK = 4;

export const MOCK_STANDINGS: StandingsTable[] = [
  {
    stage: 'REGULAR_SEASON',
    type: 'TOTAL',
    group: null,
    table: [
      {
        position: 1,
        team: { id: 65, name: 'Manchester City FC', shortName: 'Man City', tla: 'MCI', crest: 'https://crests.football-data.org/65.png' },
        playedGames: 4,
        won: 4,
        draw: 0,
        lost: 0,
        points: 12,
        goalsFor: 11,
        goalsAgainst: 3,
        goalDifference: 8,
        form: 'WWWW',
      },
      {
        position: 2,
        team: { id: 57, name: 'Arsenal FC', shortName: 'Arsenal', tla: 'ARS', crest: 'https://crests.football-data.org/57.png' },
        playedGames: 4,
        won: 3,
        draw: 1,
        lost: 0,
        points: 10,
        goalsFor: 8,
        goalsAgainst: 2,
        goalDifference: 6,
        form: 'WWDW',
      },
      {
        position: 3,
        team: { id: 64, name: 'Liverpool FC', shortName: 'Liverpool', tla: 'LIV', crest: 'https://crests.football-data.org/64.png' },
        playedGames: 4,
        won: 3,
        draw: 0,
        lost: 1,
        points: 9,
        goalsFor: 7,
        goalsAgainst: 2,
        goalDifference: 5,
        form: 'WWWL',
      },
      {
        position: 4,
        team: { id: 61, name: 'Chelsea FC', shortName: 'Chelsea', tla: 'CHE', crest: 'https://crests.football-data.org/61.png' },
        playedGames: 4,
        won: 2,
        draw: 2,
        lost: 0,
        points: 8,
        goalsFor: 8,
        goalsAgainst: 4,
        goalDifference: 4,
        form: 'WDDW',
      },
      {
        position: 5,
        team: { id: 58, name: 'Aston Villa FC', shortName: 'Villa', tla: 'AVL', crest: 'https://crests.football-data.org/58.png' },
        playedGames: 4,
        won: 2,
        draw: 1,
        lost: 1,
        points: 7,
        goalsFor: 6,
        goalsAgainst: 5,
        goalDifference: 1,
        form: 'LWDW',
      },
      {
        position: 6,
        team: { id: 67, name: 'Newcastle United FC', shortName: 'Newcastle', tla: 'NEW', crest: 'https://crests.football-data.org/67.png' },
        playedGames: 4,
        won: 2,
        draw: 1,
        lost: 1,
        points: 7,
        goalsFor: 5,
        goalsAgainst: 4,
        goalDifference: 1,
        form: 'WDWL',
      },
      {
        position: 7,
        team: { id: 73, name: 'Tottenham Hotspur FC', shortName: 'Spurs', tla: 'TOT', crest: 'https://crests.football-data.org/73.png' },
        playedGames: 4,
        won: 2,
        draw: 0,
        lost: 2,
        points: 6,
        goalsFor: 6,
        goalsAgainst: 5,
        goalDifference: 1,
        form: 'LWWL',
      },
      {
        position: 8,
        team: { id: 397, name: 'Brighton & Hove Albion FC', shortName: 'Brighton', tla: 'BHA', crest: 'https://crests.football-data.org/397.png' },
        playedGames: 4,
        won: 1,
        draw: 3,
        lost: 0,
        points: 6,
        goalsFor: 5,
        goalsAgainst: 4,
        goalDifference: 1,
        form: 'WDDD',
      },
      {
        position: 9,
        team: { id: 66, name: 'Manchester United FC', shortName: 'Man Utd', tla: 'MUN', crest: 'https://crests.football-data.org/66.png' },
        playedGames: 4,
        won: 2,
        draw: 0,
        lost: 2,
        points: 6,
        goalsFor: 5,
        goalsAgainst: 6,
        goalDifference: -1,
        form: 'WLLW',
      },
      {
        position: 10,
        team: { id: 351, name: 'Nottingham Forest FC', shortName: 'Forest', tla: 'NFO', crest: 'https://crests.football-data.org/351.png' },
        playedGames: 4,
        won: 1,
        draw: 2,
        lost: 1,
        points: 5,
        goalsFor: 4,
        goalsAgainst: 4,
        goalDifference: 0,
        form: 'DWLD',
      },
      {
        position: 11,
        team: { id: 63, name: 'Fulham FC', shortName: 'Fulham', tla: 'FUL', crest: 'https://crests.football-data.org/63.png' },
        playedGames: 4,
        won: 1,
        draw: 2,
        lost: 1,
        points: 5,
        goalsFor: 4,
        goalsAgainst: 4,
        goalDifference: 0,
        form: 'LDDW',
      },
      {
        position: 12,
        team: { id: 402, name: 'Brentford FC', shortName: 'Brentford', tla: 'BRE', crest: 'https://crests.football-data.org/402.png' },
        playedGames: 4,
        won: 1,
        draw: 1,
        lost: 2,
        points: 4,
        goalsFor: 5,
        goalsAgainst: 6,
        goalDifference: -1,
        form: 'LWDL',
      },
      {
        position: 13,
        team: { id: 1044, name: 'AFC Bournemouth', shortName: 'Bournemouth', tla: 'BOU', crest: 'https://crests.football-data.org/1044.png' },
        playedGames: 4,
        won: 1,
        draw: 1,
        lost: 2,
        points: 4,
        goalsFor: 4,
        goalsAgainst: 6,
        goalDifference: -2,
        form: 'DDLW',
      },
      {
        position: 14,
        team: { id: 354, name: 'Crystal Palace FC', shortName: 'Palace', tla: 'CRY', crest: 'https://crests.football-data.org/354.png' },
        playedGames: 4,
        won: 1,
        draw: 1,
        lost: 2,
        points: 4,
        goalsFor: 3,
        goalsAgainst: 5,
        goalDifference: -2,
        form: 'LLDW',
      },
      {
        position: 15,
        team: { id: 341, name: 'Leeds United FC', shortName: 'Leeds', tla: 'LEE', crest: 'https://crests.football-data.org/341.png' },
        playedGames: 4,
        won: 1,
        draw: 1,
        lost: 2,
        points: 4,
        goalsFor: 4,
        goalsAgainst: 7,
        goalDifference: -3,
        form: 'WLDL',
      },
      {
        position: 16,
        team: { id: 71, name: 'Sunderland AFC', shortName: 'Sunderland', tla: 'SUN', crest: 'https://crests.football-data.org/71.png' },
        playedGames: 4,
        won: 1,
        draw: 0,
        lost: 3,
        points: 3,
        goalsFor: 3,
        goalsAgainst: 6,
        goalDifference: -3,
        form: 'LLLW',
      },
      {
        position: 17,
        team: { id: 62, name: 'Everton FC', shortName: 'Everton', tla: 'EVE', crest: 'https://crests.football-data.org/62.png' },
        playedGames: 4,
        won: 1,
        draw: 0,
        lost: 3,
        points: 3,
        goalsFor: 3,
        goalsAgainst: 7,
        goalDifference: -4,
        form: 'LLWL',
      },
      {
        position: 18,
        team: { id: 349, name: 'Ipswich Town FC', shortName: 'Ipswich', tla: 'IPS', crest: 'https://crests.football-data.org/349.png' },
        playedGames: 4,
        won: 0,
        draw: 2,
        lost: 2,
        points: 2,
        goalsFor: 2,
        goalsAgainst: 6,
        goalDifference: -4,
        form: 'LLDD',
      },
      {
        position: 19,
        team: { id: 1076, name: 'Coventry City FC', shortName: 'Coventry', tla: 'COV', crest: 'https://crests.football-data.org/1076.png' },
        playedGames: 4,
        won: 0,
        draw: 1,
        lost: 3,
        points: 1,
        goalsFor: 2,
        goalsAgainst: 8,
        goalDifference: -6,
        form: 'LLDL',
      },
      {
        position: 20,
        team: { id: 322, name: 'Hull City FC', shortName: 'Hull', tla: 'HUL', crest: 'https://crests.football-data.org/322.png' },
        playedGames: 4,
        won: 0,
        draw: 1,
        lost: 3,
        points: 1,
        goalsFor: 1,
        goalsAgainst: 9,
        goalDifference: -8,
        form: 'LLLD',
      },
    ],
  },
];

// Helper to generate home and away tables
MOCK_STANDINGS.push({
  stage: 'REGULAR_SEASON',
  type: 'HOME',
  group: null,
  table: MOCK_STANDINGS[0].table.map((t, i) => ({
    ...t,
    playedGames: 2,
    won: Math.min(t.won, 2),
    draw: t.draw > 0 ? 1 : 0,
    lost: Math.max(0, 2 - Math.min(t.won, 2) - (t.draw > 0 ? 1 : 0)),
    points: Math.min(t.won, 2) * 3 + (t.draw > 0 ? 1 : 0),
  })),
});

MOCK_STANDINGS.push({
  stage: 'REGULAR_SEASON',
  type: 'AWAY',
  group: null,
  table: MOCK_STANDINGS[0].table.map((t, i) => ({
    ...t,
    playedGames: 2,
    won: Math.max(0, t.won - 2),
    draw: Math.max(0, t.draw - 1),
    lost: Math.min(t.lost, 2),
    points: Math.max(0, t.won - 2) * 3 + Math.max(0, t.draw - 1),
  })),
});

// Mock Fixtures for Matchweek 4 and 5
export const MOCK_FIXTURES: Match[] = [
  // MW 4 (Current)
  {
    id: 401,
    matchday: 4,
    utcDate: new Date(Date.now() - 3600 * 1000 * 3).toISOString(), // 3 hours ago finished
    status: 'FINISHED',
    stage: 'REGULAR_SEASON',
    venue: 'Emirates Stadium, London',
    homeTeam: { id: 57, name: 'Arsenal FC', shortName: 'Arsenal', tla: 'ARS', crest: 'https://crests.football-data.org/57.png' },
    awayTeam: { id: 73, name: 'Tottenham Hotspur FC', shortName: 'Spurs', tla: 'TOT', crest: 'https://crests.football-data.org/73.png' },
    score: {
      winner: 'HOME_TEAM',
      duration: 'REGULAR',
      fullTime: { home: 2, away: 1 },
      halfTime: { home: 1, away: 0 },
    },
  },
  {
    id: 402,
    matchday: 4,
    utcDate: new Date(Date.now() - 3600 * 1000 * 1.5).toISOString(),
    status: 'FINISHED',
    stage: 'REGULAR_SEASON',
    venue: 'Stamford Bridge, London',
    homeTeam: { id: 61, name: 'Chelsea FC', shortName: 'Chelsea', tla: 'CHE', crest: 'https://crests.football-data.org/61.png' },
    awayTeam: { id: 63, name: 'Fulham FC', shortName: 'Fulham', tla: 'FUL', crest: 'https://crests.football-data.org/63.png' },
    score: {
      winner: 'HOME_TEAM',
      duration: 'REGULAR',
      fullTime: { home: 3, away: 1 },
      halfTime: { home: 1, away: 1 },
    },
  },
  {
    id: 403,
    matchday: 4,
    utcDate: new Date(Date.now() - 60 * 1000 * 42).toISOString(), // 42 mins ago = LIVE IN_PLAY
    status: 'IN_PLAY',
    stage: 'REGULAR_SEASON',
    minute: 42,
    venue: 'Anfield, Liverpool',
    homeTeam: { id: 64, name: 'Liverpool FC', shortName: 'Liverpool', tla: 'LIV', crest: 'https://crests.football-data.org/64.png' },
    awayTeam: { id: 66, name: 'Manchester United FC', shortName: 'Man Utd', tla: 'MUN', crest: 'https://crests.football-data.org/66.png' },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: { home: 1, away: 0 },
      halfTime: { home: 1, away: 0 },
    },
  },
  {
    id: 404,
    matchday: 4,
    utcDate: new Date(Date.now() + 3600 * 1000 * 2.5).toISOString(), // In 2.5 hours
    status: 'TIMED',
    stage: 'REGULAR_SEASON',
    venue: 'Etihad Stadium, Manchester',
    homeTeam: { id: 65, name: 'Manchester City FC', shortName: 'Man City', tla: 'MCI', crest: 'https://crests.football-data.org/65.png' },
    awayTeam: { id: 58, name: 'Aston Villa FC', shortName: 'Villa', tla: 'AVL', crest: 'https://crests.football-data.org/58.png' },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: { home: null, away: null },
      halfTime: { home: null, away: null },
    },
  },
  {
    id: 405,
    matchday: 4,
    utcDate: new Date(Date.now() + 3600 * 1000 * 5).toISOString(),
    status: 'TIMED',
    stage: 'REGULAR_SEASON',
    venue: 'St. James\' Park, Newcastle',
    homeTeam: { id: 67, name: 'Newcastle United FC', shortName: 'Newcastle', tla: 'NEW', crest: 'https://crests.football-data.org/67.png' },
    awayTeam: { id: 397, name: 'Brighton & Hove Albion FC', shortName: 'Brighton', tla: 'BHA', crest: 'https://crests.football-data.org/397.png' },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: { home: null, away: null },
      halfTime: { home: null, away: null },
    },
  },
  {
    id: 406,
    matchday: 4,
    utcDate: new Date(Date.now() + 3600 * 1000 * 24).toISOString(),
    status: 'SCHEDULED',
    stage: 'REGULAR_SEASON',
    venue: 'Gtech Community Stadium, Brentford',
    homeTeam: { id: 402, name: 'Brentford FC', shortName: 'Brentford', tla: 'BRE', crest: 'https://crests.football-data.org/402.png' },
    awayTeam: { id: 351, name: 'Nottingham Forest FC', shortName: 'Forest', tla: 'NFO', crest: 'https://crests.football-data.org/351.png' },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: { home: null, away: null },
      halfTime: { home: null, away: null },
    },
  },
  {
    id: 407,
    matchday: 4,
    utcDate: new Date(Date.now() + 3600 * 1000 * 26).toISOString(),
    status: 'SCHEDULED',
    stage: 'REGULAR_SEASON',
    venue: 'Vitality Stadium, Bournemouth',
    homeTeam: { id: 1044, name: 'AFC Bournemouth', shortName: 'Bournemouth', tla: 'BOU', crest: 'https://crests.football-data.org/1044.png' },
    awayTeam: { id: 354, name: 'Crystal Palace FC', shortName: 'Palace', tla: 'CRY', crest: 'https://crests.football-data.org/354.png' },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: { home: null, away: null },
      halfTime: { home: null, away: null },
    },
  },
  {
    id: 408,
    matchday: 4,
    utcDate: new Date(Date.now() + 3600 * 1000 * 28).toISOString(),
    status: 'SCHEDULED',
    stage: 'REGULAR_SEASON',
    venue: 'Goodison Park, Liverpool',
    homeTeam: { id: 62, name: 'Everton FC', shortName: 'Everton', tla: 'EVE', crest: 'https://crests.football-data.org/62.png' },
    awayTeam: { id: 341, name: 'Leeds United FC', shortName: 'Leeds', tla: 'LEE', crest: 'https://crests.football-data.org/341.png' },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: { home: null, away: null },
      halfTime: { home: null, away: null },
    },
  },
  {
    id: 409,
    matchday: 4,
    utcDate: new Date(Date.now() + 3600 * 1000 * 30).toISOString(),
    status: 'SCHEDULED',
    stage: 'REGULAR_SEASON',
    venue: 'Portman Road, Ipswich',
    homeTeam: { id: 349, name: 'Ipswich Town FC', shortName: 'Ipswich', tla: 'IPS', crest: 'https://crests.football-data.org/349.png' },
    awayTeam: { id: 71, name: 'Sunderland AFC', shortName: 'Sunderland', tla: 'SUN', crest: 'https://crests.football-data.org/71.png' },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: { home: null, away: null },
      halfTime: { home: null, away: null },
    },
  },
  {
    id: 410,
    matchday: 4,
    utcDate: new Date(Date.now() + 3600 * 1000 * 32).toISOString(),
    status: 'SCHEDULED',
    stage: 'REGULAR_SEASON',
    venue: 'Coventry Building Society Arena',
    homeTeam: { id: 1076, name: 'Coventry City FC', shortName: 'Coventry', tla: 'COV', crest: 'https://crests.football-data.org/1076.png' },
    awayTeam: { id: 322, name: 'Hull City FC', shortName: 'Hull', tla: 'HUL', crest: 'https://crests.football-data.org/322.png' },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: { home: null, away: null },
      halfTime: { home: null, away: null },
    },
  },

  // MW 5 fixtures
  {
    id: 501,
    matchday: 5,
    utcDate: new Date(Date.now() + 3600 * 1000 * 24 * 7).toISOString(),
    status: 'SCHEDULED',
    stage: 'REGULAR_SEASON',
    venue: 'Etihad Stadium, Manchester',
    homeTeam: { id: 65, name: 'Manchester City FC', shortName: 'Man City', tla: 'MCI', crest: 'https://crests.football-data.org/65.png' },
    awayTeam: { id: 57, name: 'Arsenal FC', shortName: 'Arsenal', tla: 'ARS', crest: 'https://crests.football-data.org/57.png' },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: { home: null, away: null },
      halfTime: { home: null, away: null },
    },
  },
  {
    id: 502,
    matchday: 5,
    utcDate: new Date(Date.now() + 3600 * 1000 * 24 * 7 + 7200 * 1000).toISOString(),
    status: 'SCHEDULED',
    stage: 'REGULAR_SEASON',
    venue: 'Villa Park, Birmingham',
    homeTeam: { id: 58, name: 'Aston Villa FC', shortName: 'Villa', tla: 'AVL', crest: 'https://crests.football-data.org/58.png' },
    awayTeam: { id: 61, name: 'Chelsea FC', shortName: 'Chelsea', tla: 'CHE', crest: 'https://crests.football-data.org/61.png' },
    score: {
      winner: null,
      duration: 'REGULAR',
      fullTime: { home: null, away: null },
      halfTime: { home: null, away: null },
    },
  },
];

export const MOCK_SCORERS: Scorer[] = [
  {
    player: { id: 1, name: 'Erling Haaland', firstName: 'Erling', lastName: 'Haaland', nationality: 'Norway', section: 'Attacker', position: 'Centre-Forward' },
    team: { id: 65, name: 'Manchester City', crest: 'https://crests.football-data.org/65.png', tla: 'MCI' },
    playedMatches: 4,
    goals: 7,
    assists: 1,
    penalties: 1,
  },
  {
    player: { id: 2, name: 'Mohamed Salah', firstName: 'Mohamed', lastName: 'Salah', nationality: 'Egypt', section: 'Attacker', position: 'Right Winger' },
    team: { id: 64, name: 'Liverpool', crest: 'https://crests.football-data.org/64.png', tla: 'LIV' },
    playedMatches: 4,
    goals: 4,
    assists: 3,
    penalties: 0,
  },
  {
    player: { id: 3, name: 'Bukayo Saka', firstName: 'Bukayo', lastName: 'Saka', nationality: 'England', section: 'Attacker', position: 'Right Winger' },
    team: { id: 57, name: 'Arsenal', crest: 'https://crests.football-data.org/57.png', tla: 'ARS' },
    playedMatches: 4,
    goals: 3,
    assists: 4,
    penalties: 0,
  },
  {
    player: { id: 4, name: 'Cole Palmer', firstName: 'Cole', lastName: 'Palmer', nationality: 'England', section: 'Midfielder', position: 'Attacking Midfield' },
    team: { id: 61, name: 'Chelsea', crest: 'https://crests.football-data.org/61.png', tla: 'CHE' },
    playedMatches: 4,
    goals: 3,
    assists: 2,
    penalties: 1,
  },
  {
    player: { id: 5, name: 'Alexander Isak', firstName: 'Alexander', lastName: 'Isak', nationality: 'Sweden', section: 'Attacker', position: 'Centre-Forward' },
    team: { id: 67, name: 'Newcastle', crest: 'https://crests.football-data.org/67.png', tla: 'NEW' },
    playedMatches: 4,
    goals: 3,
    assists: 0,
    penalties: 1,
  },
];

export const MOCK_HEAD_TO_HEAD: Record<string, HeadToHead> = {
  default: {
    numberOfMatches: 10,
    totalGoals: 28,
    homeTeam: { id: 57, name: 'Arsenal', wins: 5, draws: 3, losses: 2 },
    awayTeam: { id: 73, name: 'Tottenham', wins: 2, draws: 3, losses: 5 },
  },
};

export function getMockH2H(homeName: string, awayName: string): HeadToHead {
  return {
    numberOfMatches: 6,
    totalGoals: 17,
    homeTeam: { id: 1, name: homeName, wins: 3, draws: 1, losses: 2 },
    awayTeam: { id: 2, name: awayName, wins: 2, draws: 1, losses: 3 },
  };
}

// Sample squad rosters for projected XI
export const TEAM_ROSTERS: Record<string, { starters: string[]; subs: string[]; absentees: string[] }> = {
  ARS: {
    starters: ['Raya (GK)', 'White', 'Saliba', 'Gabriel', 'Timber', 'Partey', 'Rice', 'Ødegaard (C)', 'Saka', 'Havertz', 'Martinelli'],
    subs: ['Neto', 'Kiwior', 'Zinchenko', 'Jorginho', 'Merino', 'Nwaneri', 'Sterling', 'Jesus', 'Trossard'],
    absentees: ['Tomiyasu (Knee - Late Fitness)', 'Calafiori (Calf)'],
  },
  MCI: {
    starters: ['Ederson (GK)', 'Walker (C)', 'Dias', 'Akanji', 'Gvardiol', 'Rodri', 'Kovacic', 'De Bruyne', 'Bernardo', 'Haaland', 'Foden'],
    subs: ['Ortega', 'Stones', 'Ake', 'Lewis', 'Gundogan', 'Nunes', 'Savinho', 'Doku', 'Grealish'],
    absentees: ['Bobb (Fractured Leg)'],
  },
  LIV: {
    starters: ['Alisson (GK)', 'Alexander-Arnold', 'Konate', 'Van Dijk (C)', 'Robertson', 'Gravenberch', 'Mac Allister', 'Szoboszlai', 'Salah', 'Jota', 'Diaz'],
    subs: ['Kelleher', 'Gomez', 'Quansah', 'Bradley', 'Endo', 'Jones', 'Elliott', 'Chiesa', 'Gakpo'],
    absentees: ['Bajcetic (Hamstring)'],
  },
  CHE: {
    starters: ['Sanchez (GK)', 'Gusto', 'Fofana', 'Colwill', 'Cucurella', 'Caicedo', 'Enzo (C)', 'Madueke', 'Palmer', 'Sancho', 'Jackson'],
    subs: ['Jorgensen', 'Adarabioyo', 'Badiashile', 'Veiga', 'Lavia', 'Mudryk', 'Felix', 'Neto', 'Nkunku'],
    absentees: ['James (Hamstring - Doubt)', 'Chilwell (Illness)'],
  },
  MUN: {
    starters: ['Onana (GK)', 'Mazraoui', 'De Ligt', 'Martinez', 'Dalot', 'Mainoo', 'Ugarte', 'Fernandes (C)', 'Amad', 'Højlund', 'Rashford'],
    subs: ['Bayindir', 'Maguire', 'Evans', 'Casemiro', 'Eriksen', 'Mount', 'Antony', 'Garnacho', 'Zirkzee'],
    absentees: ['Shaw (Calf)', 'Malacia (Knee)', 'Yoro (Metatarsal)'],
  },
  TOT: {
    starters: ['Vicario (GK)', 'Porro', 'Romero', 'Van de Ven', 'Udogie', 'Sarr', 'Bentancur', 'Maddison', 'Kulusevski', 'Solanke', 'Son (C)'],
    subs: ['Forster', 'Dragusin', 'Spence', 'Gray', 'Bissouma', 'Bergvall', 'Johnson', 'Werner', 'Richarlison'],
    absentees: ['Richarlison (Muscle - Late Test)', 'Odobert (Hamstring)'],
  },
  AVL: {
    starters: ['Martinez (GK)', 'Cash', 'Konsa', 'Pau Torres', 'Digne', 'Onana', 'Tielemans', 'McGinn (C)', 'Rogers', 'Bailey', 'Watkins'],
    subs: ['Olsen', 'Nedeljkovic', 'Bogarde', 'Barkley', 'Buendia', 'Ramsey', 'Philogene', 'Duran'],
    absentees: ['Kamara (ACL recovery)', 'Mings (Match Fitness)'],
  },
  NEW: {
    starters: ['Pope (GK)', 'Livramento', 'Schar', 'Burn', 'Hall', 'Guimaraes (C)', 'Tonali', 'Joelinton', 'Gordon', 'Isak', 'Barnes'],
    subs: ['Dubravka', 'Krafth', 'Kelly', 'Targett', 'Longstaff', 'Willock', 'Almiron', 'Murphy', 'Osula'],
    absentees: ['Botman (Knee)', 'Lascelles (Knee)', 'Wilson (Back)'],
  },
};

export function getTeamRoster(tla: string) {
  if (TEAM_ROSTERS[tla]) return TEAM_ROSTERS[tla];
  return {
    starters: [
      'Keeper (GK)', 'Right Back', 'Center Back A', 'Center Back B', 'Left Back',
      'Defensive Mid', 'Central Mid A', 'Central Mid B',
      'Right Wing', 'Center Forward', 'Left Wing'
    ],
    subs: ['Backup GK', 'Defender 1', 'Defender 2', 'Midfielder 1', 'Midfielder 2', 'Winger 1', 'Striker 1'],
    absentees: ['Key Defender (Muscle Strain)', 'Midfielder (Knock)'],
  };
}
